###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '3.4'

services:

  hydra-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
#      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://root@host.docker.internal:26257/hydra?sslmode=disable
    #command:
    #  migrate sql -e
    tty: true
    restart: on-failure
    # Nota, primero rular:
    # $> migrate sql -e
    # Luego:
    # $> hydra serve
    # Para comprobar que funciona la migracion realizada

  hydra:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - hydra-migrate
    ports:
      - "4444:4444"
      - "4445:4445"
    command:
      hydra serve --dangerous-force-http
    environment:
#      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://localhost:4444
      - OAUTH2_CONSENT_URL=http://localhost:3000/consent
      - OAUTH2_LOGIN_URL=http://localhost:3000/login
      - DATABASE_URL=postgres://root@host.docker.internal:26257/hydra?sslmode=disable
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - OAUTH2_SHARE_ERROR_DEBUG=1
    restart: unless-stopped

  consent:
    environment:
      - HYDRA_URL=http://hydra:4444
    image: oryd/hydra-login-consent-node:v1.0.0-beta.1
    ports:
      - "3000:3000"
    restart: unless-stopped
